ApisOlimpo/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from django.urls import path,include
from olimpo import views

urlpatterns = [
    path('',views.home),
    path('formularios/', include("formularios.urls")),
    path('administrador/',views.admin),
    path('administrador/',include('administrador.urls')),
    path('amadellaves/',include('amallaves.urls')),
    path('adicionales/',include('meseriyromm.urls')),
    # path('reserva/',include('reserva.urls')),
    path('reservaClient/',include('olimpo.urls')),



    # path('admin/', admin.site.urls),
    # path('apis/',include('apia.urls'))

]

apia/urls.py
from django.urls import path,include

from rest_framework import routers

from apia import views

router_tipo_empleado =routers.DefaultRouter()
router_tipo_empleado.register(r"tipo_empleado", views.viw_tipo_empleado)

router_estado_empleados =routers.DefaultRouter()
router_estado_empleados.register(r"estado_empleados", views.viw_estado_empleados)

router_empleados =routers.DefaultRouter()
router_empleados.register(r"empleados", views.viw_empleados)

router_estado_cliente=routers.DefaultRouter()
router_estado_cliente.register(r"estado_cliente", views.viw_estado_cliente)

router_tipo_documento=routers.DefaultRouter()
router_tipo_documento.register(r"tipo_documento", views.viw_tipo_documento)

router_cliente=routers.DefaultRouter()
router_cliente.register(r"cliente", views.viw_cliente)

router_tipo_habitacion=routers.DefaultRouter()
router_tipo_habitacion.register(r"tipo_habitacion", views.viw_tipo_habitacion)

router_estado_habitacion=routers.DefaultRouter()
router_estado_habitacion.register(r"estado_habitacion", views.viw_estado_habitacion)

router_mobiliario=routers.DefaultRouter()
router_mobiliario.register(r"mobiliario", views.viw_mobiliario)

router_habitacion=routers.DefaultRouter()
router_habitacion.register(r"habitacion", views.viw_habitacion)

router_estado_reserva=routers.DefaultRouter()
router_estado_reserva.register(r"estado_reserva", views.viw_estado_reserva)

router_reserva=routers.DefaultRouter()
router_reserva.register(r"reserva", views.viw_reserva)

router_huspedes_reserva=routers.DefaultRouter()
router_huspedes_reserva.register(r"huspedes_reserva", views.viw_huspedes_reserva)

router_servicios=routers.DefaultRouter()
router_servicios.register(r"servicios", views.viw_servicios)

router_adicionales=routers.DefaultRouter()
router_adicionales.register(r"adicionales", views.viw_adicionales)

router_detalles_factura=routers.DefaultRouter()
router_detalles_factura.register(r"detalles_factura", views.viw_detalles_factura)

router_factura=routers.DefaultRouter()
router_factura.register(r"factura", views.viw_factura)

urlpatterns = [
path("tipo_empleado/",include(router_tipo_empleado.urls)),
path("estado_empleados/",include(router_estado_empleados.urls)) ,
path("empleados/",include(router_empleados.urls)) ,
path("estado_cliente/",include(router_estado_cliente.urls)),
path("tipo_documento/",include(router_tipo_documento.urls)),
path("cliente/",include(router_cliente.urls)),
path("tipo_habitacion/",include(router_tipo_habitacion.urls)),
path("estado_habitacion/",include(router_estado_habitacion.urls)),
path("mobiliario/",include(router_mobiliario.urls)),
path("habitacion/",include(router_habitacion.urls)),
path("estado_reserva/",include(router_estado_reserva.urls)),
path("reserva/",include(router_reserva.urls)),
path("huspedes_reserva/",include(router_huspedes_reserva.urls)),
path("servicios/",include(router_servicios.urls)),
path("adicionales/",include(router_adicionales.urls)),
path("detalles_factura/",include(router_detalles_factura.urls)),
path("factura/",include(router_factura.urls)),
]

formularios/urls.py
from django.contrib import admin
from django.urls import path,include
from formularios import views


urlpatterns = [
    path('registro/',views.registro),
    path('login/', views.mostrarinicio,name="login1"),
    path('login/verifi/', views.inicio),
    path('logout/', views.cerrar_sesion, name='logout'),
    path('administrador/',include('administrador.urls')),



]

apia/models.py
from django.db import models

# Create your models here.

#empleados 
class tipo_empleado (models.Model) :
    tipo_empleado=models.CharField(max_length=20 ,primary_key=True)
    def __str__(self):
        return self.tipo_empleado

#---
class estado_empleados(models.Model):
    esatado_empleado =models.CharField(max_length=20 ,primary_key=True)
#---
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager

class empleados(AbstractBaseUser):
    cc_usu =models.CharField(max_length=20 ,primary_key=True)
    nombre =models.CharField(max_length=30)
    apellido=models.CharField(max_length=30)
    direcion=models.CharField(max_length=80)
    contacto_ememergenci=models.CharField(max_length=20)
    nombre_contacto=models.CharField(max_length=30)
    telefono=models.CharField(max_length=15)
    correo=models.CharField(max_length=70)
    eps=models.CharField(max_length=20)
    contrasenaU=models.CharField(max_length=400)
    last_login = models.DateTimeField(("last login"), blank=True, null=True)
    caja_de_compensacion=models.CharField(max_length=50)
    codigo_usu=models.ForeignKey(tipo_empleado,null=True,blank=True,on_delete=models.CASCADE)
    estado=models.ForeignKey(estado_empleados ,null=True,blank=True,on_delete=models.CASCADE)
    usuario_administrador=models.BooleanField(default=False)

    USERNAME_FIELD="cc_usu"
    REQUIRED_FIELDS=["correo","nombre"]
    
    def __str__(self):
        return f'{self.cc_usu}'
    
    def has_perm(self,perm,obj =None):
        return True
    
    def has_module_perms(self,app_label):
        return True
    @property
    def is_staff(self):
        return self.usuario_administrador
#---

# relacionado con reserva-------------------
     
class estado_cliente (models.Model):
    estado=models.CharField(max_length=20 ,primary_key=True)
    
#---
class tipo_documento (models.Model):
    tipo_documento=models.CharField(max_length=25 ,primary_key=True)
    def __str__(self):
        return self.tipo_documento

#--- cliente --------------------------------


class cliente (models.Model):
    numero_doc = models.CharField(max_length=20, primary_key=True, verbose_name="Número de Documento")
    correo = models.CharField(max_length=100, verbose_name="Correo")
    nombre = models.CharField(max_length=50, verbose_name="Nombre")
    numero_contacto = models.CharField(max_length=25, verbose_name="Número de Contacto")
    contrasenaaC = models.CharField(max_length=400, verbose_name="Contraseña")
    estado = models.ForeignKey(estado_cliente, default='Activo', null=True, blank=True, on_delete=models.CASCADE, verbose_name="Estado")
    tipo_doc = models.ForeignKey(tipo_documento, null=True, blank=True, on_delete=models.CASCADE, verbose_name="Tipo de Documento")
    last_login = models.DateTimeField(("last login"), blank=True, null=True)

#---
class tipo_habitacion (models.Model):
    tipo_habitacion=models.CharField(max_length=25 ,primary_key=True)
#---
class estado_habitacion (models.Model):
    estado_reserva=models.CharField(max_length=25 ,primary_key=True)

#---
class mobiliario (models.Model):
    id_mobi=models.CharField(max_length=20 ,primary_key=True)
    camas_sencillas=models.CharField(max_length=20)
    camas_doble=models.CharField(max_length=20)
    camas_king=models.CharField(max_length=20)
    tv_plano=models.CharField(max_length=20)
    sala=models.CharField(max_length=20)
    sillas=models.CharField(max_length=20)
    
#---
class habitacion (models.Model):
    numero_H=models.CharField(max_length=20 ,primary_key=True)
    cantidad_p=models.CharField(max_length=20)
    valor_habitacion=models.FloatField()

    id_mobi=models.ForeignKey(mobiliario ,null=True,blank=True,on_delete=models.CASCADE)
    estado=models.ForeignKey(estado_habitacion ,null=True,blank=True,on_delete=models.CASCADE)
    tipo =models.ForeignKey(tipo_habitacion ,null=True,blank=True,on_delete=models.CASCADE)

#---
class estado_reserva (models.Model):
    estado_reserva=models.CharField(max_length=25 ,primary_key=True)
#---

class reserva (models.Model):
    id_reserva=models.AutoField(primary_key=True)    
    fecah_ini=models.DateTimeField(auto_now = False)
    fecah_fin=models.DateTimeField(auto_now = False)
    valor_reserva=models.FloatField()

    habitacion=models.ForeignKey(habitacion ,null=True,blank=True,on_delete=models.CASCADE)
    numero_doc=models.ForeignKey(cliente ,null=True,blank=True,on_delete=models.CASCADE)
    estado_res=models.ForeignKey(estado_reserva ,null=True,blank=True,on_delete=models.CASCADE)

#---
class huspedes_reserva(models.Model):
    
    id_reserva=models.ForeignKey(reserva ,null=True,blank=True,on_delete=models.CASCADE)
    numero_doc=models.ForeignKey(cliente ,null=True,blank=True,on_delete=models.CASCADE)


#servivios y adiciona les factura-----------------------------------
    
class servicios (models.Model):
    tipo_servicio=models.CharField(max_length=25 ,primary_key=True)

#---
class adicionales(models.Model):
    id_adi=models.AutoField(primary_key=True)  
    descripcion=models.CharField(max_length=300)
    valor=models.FloatField()

    id_servi=models.ForeignKey(servicios ,null=True,blank=True,on_delete=models.CASCADE)
    empleado_A_cargo=models.ForeignKey(empleados ,null=True,blank=True,on_delete=models.CASCADE) 
    id_reserva=models.ForeignKey(reserva ,null=True,blank=True,on_delete=models.CASCADE)
#---

class detalles_factura(models.Model):
    id_factura=models.AutoField(primary_key=True) 
    valor_reserva=models.FloatField()
    valor_adicional=models.FloatField()

    id_reserva=models.ForeignKey(reserva ,null=True,blank=True,on_delete=models.CASCADE)
    id_adi=models.ForeignKey(adicionales ,null=True,blank=True,on_delete=models.CASCADE)

#---
    
class factura(models.Model):
    id_factura=models.AutoField(primary_key=True)
    pago_total=models.FloatField()
    fecha=models.DateTimeField()
    
    empleado_A_cargo=models.ForeignKey(empleados ,null=True,blank=True,on_delete=models.CASCADE)

formularios/models.py
from django.db import models

# Create your models here.

formularios/forms.py
from django import forms
from django.http import HttpResponse
from apia.models import cliente, tipo_documento, empleados, tipo_empleado
from django.contrib.auth import authenticate, login




class registrocliente(forms.ModelForm):
    
    tipo_doc = forms.ModelChoiceField(queryset=tipo_documento.objects.all(), required=True, label="Tipo de Documento")
    contrasenaaC = forms.CharField(widget=forms.PasswordInput, label="Contraseña")

    def __init__(self, *args, **kwargs):
        super(registrocliente, self).__init__(*args, **kwargs)
        self.fields['tipo_doc'].label_from_instance = lambda obj: "%s" % obj.tipo_documento

    class Meta:
        model = cliente
        fields = ['tipo_doc', 'numero_doc', 'correo', 'nombre', 'numero_contacto', 'contrasenaaC']


class loginclientes(forms.Form):
    tipo_usuario = forms.ModelChoiceField(queryset=tipo_empleado.objects.all(), label="Tipo de Usuario")
    def __init__(self, *args, **kwargs):
        super(loginclientes, self).__init__(*args, **kwargs)
        self.fields['tipo_usuario'].label_from_instance = lambda obj: "%s" % obj.tipo_empleado

    numero_doc = forms.CharField(required=True)
    contrasenaaC = forms.CharField(widget=forms.PasswordInput, required=True)

formularios/views.py
import hashlib
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import registrocliente, loginclientes
from django.contrib.auth import authenticate, login, logout
from apia.models import cliente, empleados
from django.contrib.auth.hashers import check_password
from django.contrib.auth.decorators import login_required





# Create your views here.

def registro(request):
    if request.method == "POST":
        cliente_form = registrocliente(request.POST)
        if cliente_form.is_valid():
            numero_doc = cliente_form.cleaned_data.get('numero_doc')
            if cliente.objects.filter(numero_doc=numero_doc).exists():
                return HttpResponse('<script>alert("Ya hay un usuario con el mismo documento"); window.location="/formularios/login/";</script>')
            if empleados.objects.filter(cc_usu=numero_doc).exists():
                return HttpResponse('<script>alert("Usted es un empleado"); window.location="/formularios/login/";</script>')
            else:
                contrasenaaC = cliente_form.cleaned_data.get('contrasenaaC')
                h = hashlib.sha256()
                h.update(contrasenaaC.encode())
                password_hash = h.hexdigest()
                nuevo_cliente = cliente_form.save(commit=False) 
                nuevo_cliente.contrasenaaC = password_hash
                nuevo_cliente.save()
                cliente_form.save()
                return redirect("/")
    else:
        cliente_form = registrocliente()

    return render(request, "registro.html", {'form': cliente_form})


def authenticate_cliente(numero_doc=None, password=None):
    try:
        cliente_obj = cliente.objects.get(numero_doc=numero_doc)
        h = hashlib.sha256()
        h.update(password.encode())
        password_hash = h.hexdigest()

        if password_hash == cliente_obj.contrasenaaC:
            return cliente_obj
    except cliente.DoesNotExist:
        pass
    return None

def authenticate_empleado(numero_doc_e=None, password_e=None, tipo = None):
    try:
        empleado_obj = empleados.objects.get(cc_usu=numero_doc_e)

        if check_password(password_e, empleado_obj.password):
            return empleado_obj
    except empleados.DoesNotExist:
        pass
    return None

def inicio(request):
    if request.method == "POST":
        print("a")
        documento1 = request.POST.get("numero_doc")  
        password1 = request.POST.get("contrasenaaC")  
        tipo_usu = request.POST.get("tipo_usuario")
        
        print("Documento ingresado:", documento1)  
        print("Contraseña ingresada:", password1)  
        print("tipo usuario:", tipo_usu)


        if tipo_usu == "cliente":
            print("cliente tall1")
            user = authenticate_cliente(numero_doc=documento1, password=password1)
            if user is not None:
                user_au = True
                login(request, user)
                print("Autenticación exitosa")
                print(request.user)
                nombre_usuario = user.nombre
                print(nombre_usuario)
                return render(request, "index.html", {"user_au": user_au, "name": nombre_usuario})
            else:
                return HttpResponse('<script>alert("Credenciales Incorrectas"); window.location="/formularios/login/";</script>')


        elif tipo_usu == "Administrador":
            empleado = authenticate_empleado(numero_doc_e=documento1, password_e=password1)
            if empleado is not None:
                login(request, empleado)
                print("autenticacion correcta empleado")
                return redirect("/administrador/")
            else:
                return HttpResponse('<script>alert("Credenciales Incorrectas"); window.location="/formularios/login/";</script>')
            
        elif tipo_usu == "resepcionista":

            empleado = authenticate_empleado(numero_doc_e=documento1, password_e=password1)
            if empleado is not None:
                login(request, empleado)
                print("autenticacion correcta empleado")
                return redirect( "/recepcionista/recepcionista/")
            else:
                return HttpResponse('<script>alert("Credenciales Incorrectas"); window.location="/formularios/login/";</script>')
        
        elif tipo_usu == "ama_de_llaves":
            empleado = authenticate_empleado(numero_doc_e=documento1, password_e=password1)
            if empleado is not None:
                login(request, empleado)
                print("autenticacion correcta empleado")
                return redirect("/amadellaves/accionamadellaves/")
            else:
                return HttpResponse('<script>alert("Credenciales Incorrectas"); window.location="/formularios/login/";</script>')

        elif tipo_usu == "camarero" or "room_service":
            empleado = authenticate_empleado(numero_doc_e=documento1, password_e=password1)
            if empleado is not None:
                login(request, empleado)
                print("autenticacion correcta empleado")
                return redirect( "/adicionales/meseros/")
            else:
                return HttpResponse('<script>alert("Credenciales Incorrectas"); window.location="/formularios/login/";</script>')

        else:
            print("Credenciales inválidas")

    return redirect('login/')


    
def mostrarinicio(request):
    loginc = loginclientes(request.POST)
    return render(request, 'login.html', {'form': loginc})

def cerrar_sesion(request):
    logout(request)
    return redirect('/')

formularios/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inicio Sesion</title>
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
</head>

<body>
    <div class="containerr forms">
        <div class="form login">
            <div class="form-content">
                <header><strong>Login</strong></header>
                <!-- <h5>Complete todos los campos</h5> -->
                <form method="post" action="verifi/">
                    {% csrf_token %}
                    <div class="field">
                        <label for="id_tipo_usuario">Ingrese tipo de usuario</label>
                        {{ form.tipo_usuario }}
                    </div>
                    <div class="field">
                        <label for="id_numero_doc">Ingrese documento</label>
                        {{ form.numero_doc }}
                    </div>
                    <div class="field">
                        <label for="id_contrasenaaC">Ingrese contraseña</label>
                        {{ form.contrasenaaC }}
                    </div>
                    <div class="field button-field">
                        <input type="submit" value="Ingresar" class="btn btn-success float-right">
                    </div>
                    <div class="form-link">
                        <span>¿No tienes cuenta? <a href="/formularios/registro/">Regístrate aquí</a></span>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </form>
    </div>
    </div>


    </div>
</body>
<style>
    @import url('https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800,900&display=swap');

    * {
        margin: 0;
        padding: 0;
        box-sizing: 0;
        font-family: 'Poppins';
    }

    .containerr {
        height: 100vh;
        width: 100%;
        display: flex;
        align-items: center;
        justify-content: center;
        background-color: rgb(182, 171, 121);
    }

    header {
        font-size: 28px;
        font-weight: 600px;

        color: black;
        text-align: center;
        padding: 10px;
    }

    .form {
        max-width: 430px;
        width: 100%;
        padding: 30px;
        border: 1px solid #ccc;
        border-radius: 6px;
        background-color: #fff;
    }


    .field select {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 3px;
        appearance: none;
        -webkit-appearance: none;
        -moz-appearance: none;
        background-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="%23333" d="M14.641 7.359l-4 4-4-4a.5.5 0 1 0-.707.707l4.146 4.146a1 1 0 0 0 1.414 0l4.146-4.146a.5.5 0 0 0-.707-.707z"/></svg>');
        background-repeat: no-repeat;
        background-position: right 8px center;
    }

    .field {
        margin-bottom: 15px;
    }

    .field input[type="text"],
    .field input[type="password"] {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 3px;
    }

    .button-field input[type="submit"] {
        width: 100%;
        padding: 10px;
        background-color: rgb(182, 171, 121);
        color: #fff;
        border: none;
        border-radius: 3px;
        cursor: pointer;
    }

    .button-field input[type="submit"]:hover {
        background-color: rgb(185, 166, 82);
    }

    .form-link {
        text-align: center;
        margin-top: 15px;
    }

    .form-link a {
        color: #007bff;
        text-decoration: none;
    }

    .form-link a:hover {
        text-decoration: underline;
    }
</style>

</html>

formularios/templates/registro.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro</title>
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
</head>
<body>
<div class="containerr forms">
    <div class="form login">
        <div class="form-content">
            <header><strong>Registro</strong></header>
            <form method="post" action="">
              {% csrf_token %}
              <div class="field">
                  <label for="id_tipo_doc">Ingrese tipo de documento</label>
                  {{ form.tipo_doc }}
              </div>
              <div class="field">
                  <label for="id_numero_doc">Ingrese número de documento</label>
                  {{ form.numero_doc }}
              </div>
              <div class="field">
                  <label for="id_correo">Ingrese correo electrónico</label>
                  {{ form.correo }}
              </div>
              <div class="field">
                  <label for="id_nombre">Ingrese nombre</label>
                  {{ form.nombre }}
              </div>
              <div class="field">
                  <label for="id_numero_contacto">Ingrese número de contacto</label>
                  {{ form.numero_contacto }}
              </div>
              <div class="field">
                  <label for="id_contrasenaaC">Ingrese contraseña</label>
                  {{ form.contrasenaaC }}
              </div>
              <div class="field button-field">
                  <input type="submit" value="Registrarse" class="btn btn-success float-right">
              </div>
              <div class="form-link">
                  <span>¿Ya tienes cuenta? <a href="/formularios/login/">Inicia sesión aquí</a></span>
              </div>
          </form>
        </div>
    </div>
</div>
</form>
</div>
</div>


</div>
</body>
<style>
    @import url('https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800,900&display=swap');

    * {
        margin: 0;
        padding: 0;
        box-sizing: 0;
        font-family: 'Poppins';
    }

    .containerr {
        height: 100vh;
        width: 100%;
        display: flex;
        align-items: center;
        justify-content: center;
        background-color: rgb(182, 171, 121);
    }

    header {
        font-size: 28px;
        font-weight: 600px;
        
        color: black;
        text-align: center;
        padding: 10px;
    }

    .form {
        max-width: 430px;
        width: 100%;
        padding: 30px;
        border: 1px solid #ccc;
        border-radius: 6px;
        background-color: #fff;
    }
    

    .field select {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 3px;
        appearance: none;
        -webkit-appearance: none;
        -moz-appearance: none;
        background-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="%23333" d="M14.641 7.359l-4 4-4-4a.5.5 0 1 0-.707.707l4.146 4.146a1 1 0 0 0 1.414 0l4.146-4.146a.5.5 0 0 0-.707-.707z"/></svg>');
        background-repeat: no-repeat;
        background-position: right 8px center;
    }

    .field {
        margin-bottom: 15px;
    }

    .field input[type="text"],
    .field input[type="password"] {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 3px;
    }

    .button-field input[type="submit"] {
        width: 100%;
        padding: 10px;
        background-color: rgb(182, 171, 121);
        color: #fff;
        border: none;
        border-radius: 3px;
        cursor: pointer;
    }

    .button-field input[type="submit"]:hover {
        background-color: rgb(185, 166, 82);
    }

    .form-link {
        text-align: center;
        margin-top: 15px;
    }

    .form-link a {
        color: #007bff;
        text-decoration: none;
    }

    .form-link a:hover {
        text-decoration: underline;
    }
</style>

</html>